#!/bin/bash

# Doc: http://wiki.debian.org/MaintainerScripts

#DEBHELPER#

case "$1" in

  purge)
    # Remove the Debian system user/group.
    deluser --quiet --remove-home oversip &>/dev/null || true

    # Remove the Ruby gem.
    echo "uninstalling 'oversip' Ruby Gem(s)..."
    gem1.9.1 uninstall oversip -a -x -I
    ;;

esac

exit 0

#DEBHELPER#
