#!/bin/bash

# Doc: http://wiki.debian.org/MaintainerScripts

#DEBHELPER#

OVERSIP_GEM_VERSION="~>1.1.0.beta2"

set -e

install_gem() {
  echo "installing 'oversip' Ruby Gem (version $OVERSIP_GEM_VERSION)..."
  gem1.9.1 install oversip --no-rdoc --no-ri -v $OVERSIP_GEM_VERSION
}

case "$1" in

  install)
    # Add a Debian system user/group called "oversip".
    adduser --quiet --system --group --disabled-password \
            --shell /bin/false --gecos "OverSIP" \
            --home /var/run/oversip oversip || true

    # Install the Ruby gem.
    install_gem
    ;;

  upgrade)
    # Install the Ruby gem.
    install_gem
    ;;

esac

exit 0

#DEBHELPER#