#!/bin/bash

# Doc: http://wiki.debian.org/MaintainerScripts

#DEBHELPER#

set -e


OVERSIP_GEM_VERSION="2.0.3"


install_gem() {
  #echo "uninstalling (previous) 'oversip' Ruby Gem(s)..."
  #set +e
  #gem1.9.1 uninstall oversip -a -x -I
  #set -e
  echo "installing 'oversip' Ruby Gem version $OVERSIP_GEM_VERSION..."
  gem install oversip --no-rdoc --no-ri -v $OVERSIP_GEM_VERSION
}

case "$1" in

  install)
    # Add a Debian system user/group called "oversip".
    adduser --quiet --system --group --disabled-password \
            --shell /bin/false --gecos "OverSIP" \
            --home /var/run/oversip oversip || true

    # Install the Ruby gem.
    install_gem
    ;;

  upgrade)
    # Install the Ruby gem.
    install_gem
    ;;

esac

exit 0

#DEBHELPER#
